# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bunjang_ios_day' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bunjang_ios_day

  pod 'ImageSlideshow', '~> 1.9.0'
  pod 'Tabman', '~> 2.11'
  pod 'Alamofire'

end
